version: '3'
services:
    redis:
        image: "redis"
    currency_converter:
        build:
            context: currency_converter/
        image: "currency_converter"
        depends_on:
            - redis
        ports:
            - "5000:5000"
    forex:
        build:
            context: forex/
        image: "forex"
        depends_on:
            - redis
