#!/usr/bin/env python3
from configparser import ConfigParser
import json

from flask import Flask, request

from currency.converter import Converter
from currency.json_generator import JsonGenerator


app = Flask(__name__)
config = ConfigParser()
config.read("/etc/currency_converter/config.ini")

converter = Converter(config)
json_generator = JsonGenerator(converter)


@app.route('/currency_converter')
def currency_converter():
    try:
        amount = request.args.get("amount", default=1)
        input_currency = request.args.get("input_currency")
        output_currency = request.args.get("output_currency", default="ALL")

        if input_currency is None:
            raise ValueError("input_currency must be specified")

        return json_generator.create_json(
            input_currency, output_currency, amount)
    except ValueError as e:
        return json.dumps({"error": str(e)})


def main():
    app.run(host='0.0.0.0')


if __name__ == "__main__":
    main()
